### PR TITLE
Missing import of sortable.

### PR DESCRIPTION
**Pull request by yariplus**

### CODE REVIEW

**Comment by zetas** [comment]
Hey @yariplus thanks for this PR, all the sudden I wasn't able to sort the featured topics anymore. I don't know what triggered it, i didn't update the plugin or nodebb. It was very mysterious. Anyway, I merged your PR but now the plugin errors out on load with the following error message in the logs:
`
error: [plugins/nodebb-plugin-featured-threads] Error in plugin.json or package.json! Cannot read property 'length' of null
`

Any ideas? My plugin.json is identical to yours.

**Comment by yariplus** [comment]
The jquery import has changed, the client script needs to updated. Use  my
plugin featured-topics-extended.

**Comment by zetas** [comment]
Ahhh thanks again @yariplus. Switching out this plugin for yours did wonders. Much appreciated.

**Comment by barisusakli** [comment]
@yariplus  I think  this PR isn't valid anymore? The file in core is name jquery-ui.js without the version numbers. Let me know.

**Comment by yariplus** [comment]
Correct, this is no longer needed on latest core.

**Pull request closed without merging**
