### PR TITLE
Fix 4x1 styling, adds 2 widgets.

### PR DESCRIPTION
**Pull request by yariplus**
Adds a recent-cards-like widget and topic list widget.

### CODE REVIEW

**Comment by yariplus** [comment]
@psychobunny ping.

I'm working on a bunch of other improvements to this plugin. I didn't want to push them all at once.

People frequently ask me to make custom versions of this plugin, and I want to add the most requested features. I would rather push them to this plugin than publish my own fork. Maybe moving it to third-party is an option?

**Comment by barisusakli** [comment]
@yariplus I am updating this plugin to latest nbb and fixing some old issues, feel free to send your improvements after that

**Comment by yariplus** [comment]
Wow, very old pr

**Comment by psychobunny** [comment]
I am so sorry! haha. In the end, your plugin is pretty robust so I'm glad you worked on that instead :)

**Pull request closed without merging**
